stages:
  - build
  - tests
  - trigger

variables:
  CONTAINER: $CI_PROJECT_NAME
  IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

api_build:
  tags:
    - dev
  stage: build
  image: docker:26.0.0
  services:
    - docker:26.0.0-dind
  script:
    - docker build -t $CI_PROJECT_NAMESPACE -f Dockerfile .
    - docker tag $CI_PROJECT_NAMESPACE $IMAGE
    - docker push $IMAGE

api_tests:
  tags:
    - dev
  stage: tests
  image: python:3.11.9-slim
  # services:
  #   - python:3.11.9-slim
  before_script:
    - python3.11 --version
    - python3.11 -m pip install --upgrade pip
    - python3.11 -m pip install -r requirements.txt
    - python3.11 -m pip install -r dev-requirements.txt
  script:
    # - python3 < <(curl -s https://bootstrap.pypa.io/get-pip.py)
    - python3.11 -m pytest

deploy_trigger:
  stage: trigger
  variables:
    UPSTREAM_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  trigger: $CD_NAMESPACE
  only:
    - main
