stages:
  - build
  - trigger

variables:
  CONTAINER: $CI_PROJECT_NAME
  IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

api_build:
  stage: build
  image: docker:26.0.0
  services:
    - docker:26.0.0-dind
  script:
    - docker build -t $CI_PROJECT_NAMESPACE -f Dockerfile .
    - docker tag $CI_PROJECT_NAMESPACE $IMAGE
    - docker push $IMAGE


deploy_trigger:
  stage: trigger
  variables:
    UPSTREAM_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  trigger: $CD_NAMESPACE
  only:
    - main
